<?php
require_once __DIR__ . '/../../App/auth.php'; require_login();
$pdo=db(); $id=(int)($_GET['id']??0); if($id<=0){header('Location: utilizadores.php');exit;}
$st=$pdo->prepare('SELECT * FROM utilizadores WHERE id_utilizador=?');$st->execute([$id]);$u=$st->fetch(PDO::FETCH_ASSOC);if(!$u){header('Location: utilizadores.php');exit;}
$perfis=$pdo->query("SELECT id_perfil,nome,nivel_acesso FROM perfis WHERE estado='ATIVO' ORDER BY nome")->fetchAll(PDO::FETCH_ASSOC);
$ramos=$pdo->query("SELECT id_ramo,nome,sigla FROM ramo WHERE estado='ATIVO' ORDER BY nome")->fetchAll(PDO::FETCH_ASSOC);
$qr=$pdo->prepare('SELECT id_ramo FROM utilizador_ramo WHERE id_utilizador=?');$qr->execute([$id]);$ramosSelecionados=array_map('intval',$qr->fetchAll(PDO::FETCH_COLUMN));
$erro='';$sucesso='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $nome=trim($_POST['nome_utilizador']??'');$email=trim($_POST['email']??'');$idPerfil=(int)($_POST['id_perfil']??0);$estado=$_POST['estado']??'ATIVO';$novaSenha=$_POST['senha']??'';$ids=array_values(array_filter(array_map('intval',$_POST['ramos']??[])));
 if($nome===''||$idPerfil<=0)$erro='Preencha o nome de utilizador e o perfil.'; else {try{$pdo->beginTransaction();$sql='UPDATE utilizadores SET nome_utilizador=?,email=?,id_perfil=?,estado=?';$vals=[$nome,$email!==''?$email:null,$idPerfil,in_array($estado,['ATIVO','INATIVO'],true)?$estado:'ATIVO'];if($novaSenha!==''){$sql.=',senha=?';$vals[]=password_hash($novaSenha,PASSWORD_DEFAULT);} $sql.=' WHERE id_utilizador=?';$vals[]=$id;$q=$pdo->prepare($sql);$q->execute($vals);
  $pdo->prepare('DELETE FROM utilizador_ramo WHERE id_utilizador=?')->execute([$id]);$qr=$pdo->prepare('INSERT INTO utilizador_ramo(id_utilizador,id_ramo) VALUES(?,?)');foreach($ids as $rid)$qr->execute([$id,$rid]);
  if(!empty($_FILES['foto']['name'])&&is_uploaded_file($_FILES['foto']['tmp_name'])){$ext=strtolower(pathinfo($_FILES['foto']['name'],PATHINFO_EXTENSION));if(!in_array($ext,['jpg','jpeg','png','webp'],true))throw new RuntimeException('Formato de foto não permitido.');$dir=app_public_path('uploads/utilizadores');if(!is_dir($dir))mkdir($dir,0775,true);$file='utilizador_'.$id.'_'.bin2hex(random_bytes(5)).'.'.$ext;if(!move_uploaded_file($_FILES['foto']['tmp_name'],$dir.DIRECTORY_SEPARATOR.$file))throw new RuntimeException('Não foi possível guardar a foto.');$rel='uploads/utilizadores/'.$file;$pdo->prepare('UPDATE utilizadores SET foto=? WHERE id_utilizador=?')->execute([$rel,$id]);$u['foto']=$rel;}
  $pdo->commit();$st=$pdo->prepare('SELECT * FROM utilizadores WHERE id_utilizador=?');$st->execute([$id]);$u=$st->fetch(PDO::FETCH_ASSOC);$ramosSelecionados=$ids;if((int)($_SESSION['user']['id']??0)===$id){$_SESSION['user']['nome']=$u['nome_utilizador'];$_SESSION['user']['perfil']=$pdo->query('SELECT nome FROM perfis WHERE id_perfil='.(int)$u['id_perfil'])->fetchColumn() ?: $_SESSION['user']['perfil'];$_SESSION['user']['foto']=$u['foto'];$_SESSION['user']['tema']=$u['tema'];} $sucesso='Utilizador atualizado com sucesso.';
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$erro=$e->getMessage()==='Não foi possível guardar a foto.'?$e->getMessage():(str_contains($e->getMessage(),'Duplicate')?'O nome de utilizador ou e-mail já existe.':'Não foi possível atualizar o utilizador.');}}
}
require __DIR__.'/../layout/header.php';
?>
<div class="module-page module-utilizador-form"><div class="form-panel panel"><div class="page-header"><div><h1>Editar Utilizador</h1><p>Dados, fotografia, senha, perfil e ramos de <?=htmlspecialchars($u['nome_utilizador'])?>.</p></div></div><?php if($erro):?><div class="erro"><?=htmlspecialchars($erro)?></div><?php endif;?><?php if($sucesso):?><div class="alert-sucesso"><?=htmlspecialchars($sucesso)?></div><?php endif;?><form method="post" enctype="multipart/form-data" class="form-grid">
<div class="foto-edicao full"><div class="foto-edicao-preview"><?php if(!empty($u['foto'])):?><img src="<?=htmlspecialchars(app_file_url($u['foto']))?>" alt="Foto do utilizador"><?php else:?><span><?=htmlspecialchars(strtoupper(substr($u['nome_utilizador'],0,1)))?></span><?php endif;?></div><div><strong>Fotografia</strong><small>Escolha uma nova imagem para substituir a atual.</small><input type="file" name="foto" accept="image/jpeg,image/png,image/webp"></div></div>
<label>Nome de utilizador<input required name="nome_utilizador" value="<?=htmlspecialchars($u['nome_utilizador'])?>"></label><label>E-mail<input type="email" name="email" value="<?=htmlspecialchars($u['email']??'')?>"></label>
<label>Nova senha<input type="password" name="senha" placeholder="Deixe vazio para manter a atual"></label><label>Perfil<select required name="id_perfil"><?php foreach($perfis as $p):?><option value="<?=$p['id_perfil']?>" <?=$u['id_perfil']==$p['id_perfil']?'selected':''?>><?=htmlspecialchars($p['nome'])?></option><?php endforeach;?></select></label>
<label class="full">Ramos<select name="ramos[]" multiple size="5"><?php foreach($ramos as $r):?><option value="<?=$r['id_ramo']?>" <?=in_array((int)$r['id_ramo'],$ramosSelecionados,true)?'selected':''?>><?=htmlspecialchars(($r['sigla']?:$r['nome']).' — '.$r['nome'])?></option><?php endforeach;?></select></label>
<label>Estado<select name="estado"><option value="ATIVO" <?=$u['estado']==='ATIVO'?'selected':''?>>ATIVO</option><option value="INATIVO" <?=$u['estado']==='INATIVO'?'selected':''?>>INATIVO</option></select></label>
<div class="full actions"><button class="btn btn-primary">Guardar alterações</button><a class="btn btn-secondary" href="utilizadores.php">Voltar</a></div></form></div></div>
<?php require __DIR__.'/../layout/footer.php'; ?>
